# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LIST": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Kelvinthedrugger.github.io/slow_nn/"

git_url = "https://github.com/Kelvinthedrugger/slow_nn/tree/master/"

def custom_doc_links(name): return None
