# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['LIST']

# Cell
class LIST:
    "array, supports advance indexing"
    def __init__(self,content=None):
        if not content:
            self.arr = []
        else:
            self.arr = content

    "make LIST per se subscriptable, aka, can use LIST_A'[index]' "
    def __getitem__(self,idx):
        "should we use 'yield' so that it can process async'ly?"
        return self.arr[idx]